### ISSUE TITLE
useHotkey return function doesnt work propertly

### ISSUE THREAD

**Issue by jlpereira** [Talljack/vue3-hotKey#11]
Hello,

It seems the return function doesn't work as expected. Map function is returning fuctions and not executing the function to remove each hotkey. However, if the idea is return an array of funtions, it should return the map

https://github.com/Talljack/vue3-hotKey/blob/4e39073ea455fffc37a279131551ec7cc527636e/src/useHotKey.ts#L10-L13

**Comment by Talljack** [comment]
> Hello,
> 
> It seems the return function doesn't work as expected. Map function is returning fuctions and not executing the function to remove each hotkey. However, if the idea is return an array of funtions, it should return the map
> 
> https://github.com/Talljack/vue3-hotKey/blob/4e39073ea455fffc37a279131551ec7cc527636e/src/useHotKey.ts#L10-L13

I'll see

**Comment by Talljack** [comment]
I'll return this hotkeys.map, thanks

**Comment by Talljack** [comment]
https://github.com/Talljack/vue3-hotKey/blob/main/src/useHotKey.ts#L10L12
I return this map of remove hotkey fn
