### ISSUE TITLE
Removing console.log from release.

### ISSUE THREAD

**Issue by dianlight** [Talljack/vue3-hotKey#2]
hi, 
 I have a lot of "console spam". 
Please consider removing the console.log or add a "debug" property/config to activate.

For example:
console.log("doing fixed mapping")

**Comment by Talljack** [comment]
I will delete these consoles in the production environment, and the development environment can be configured to open　@dianlight

**Comment by neoighodaro** [comment]
Hey... is this something you are still planning to do?

**Comment by Talljack** [comment]
> Hey... is this something you are still planning to do?

what do you mean?

**Comment by neoighodaro** [comment]
Not entirely sure. Used a different package so you can ignore my comment

**Comment by li-kang** [comment]
> I will delete these consoles in the production environment, and the development environment can be configured to open　

have this work done? @Talljack

**Comment by Talljack** [comment]
> > I will delete these consoles in the production environment, and the development environment can be configured to open
> 
> have this work done? @Talljack

yeah
