### ISSUE TITLE
preventDefault is invalid

### ISSUE THREAD

**Issue by MildSYang** [Talljack/vue3-hotKey#3]
my run 'ctrl + s';
but is run system save

**Comment by jmverges** [comment]
same here

**Comment by Talljack** [comment]
> same here

oh, I will see

**Comment by Talljack** [comment]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/34439652/182011553-8cb58565-1050-436d-be73-a256bc85798b.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/34439652/182011565-cf7dcc53-81f7-4965-80b0-bc0a8bbc9603.png">
I use mac has no problem, can you give me a sandbox of reproduce the problem
