### ISSUE TITLE
An Option to disable triggering handler if input or select elements have focus.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Talljack/vue3-hotKey#7]
Event is not given to handler.
Would be good to have a way to disable it on specific elements?

Can do with checking window.event.target I suppose, but might be nice to pass event down to handler.
```js
          if (window.event.target.nodeName === 'INPUT' || window.event.target.nodeName === 'SELECT' || window.event.target.nodeName === 'TEXTAREA') {
            return;
          }
```

But window.event is Deprecated.
https://developer.mozilla.org/en-US/docs/Web/API/Window/event

Propose to make it an option or provide event down to handler as an additional 2nd arg.

**Comment by Talljack** [comment]
> Event is not given to handler. Would be good to have a way to disable it on specific elements?
> 
> Can do with checking window.event.target I suppose, but might be nice to pass event down to handler.
> 
> ```js
>           if (window.event.target.nodeName === 'INPUT' || window.event.target.nodeName === 'SELECT' || window.event.target.nodeName === 'TEXTAREA') {
>             return;
>           }
> ```
> 
> But window.event is Deprecated. https://developer.mozilla.org/en-US/docs/Web/API/Window/event
> 
> Propose to make it an option or provide event down to handler as an additional 2nd arg.

yeah, I think this is ok
